# https://sansnom.org
base_url = "/"

title = "Association Sans Nom - Libre et sécurité à 42"
description = "ASN, l'association étudiante de 42 pour tout ce qui touche au Libre et à la sécurité !"

default_language = "fr"
author = "Association Sans Nom"

highlight_code = true
highlight_theme = "base16-ocean-dark"
compile_sass = true

generate_rss = true
taxonomies = [
    {name = "activities", rss = true},
]

build_search_index = true

ignored_content = []

[extra]
